### ISSUE TITLE
How to make it a modal instead of window popup?

### ISSUE THREAD

**Issue by choopage** [MurhafSousli/ng2-sharebuttons#1]
After clicking on e.g. the share button for facebook, it's now a window popup, how do I make it a modal?

**Comment by MurhafSousli** [comment]
Currently we are using 
````
click(){
    window.open(this.link,'newwindow', this.windowAttr);
  }
```
but I like the idea, maybe we can embed it in a modal

**Comment by MurhafSousli** [comment]
@choopage After I implemented the modal I found out that it is not possible, because they have set the header to `SAMEORIGIN` , which means that they have disallowed loading of the resource in an `iframe` outside of their domain. So this `iframe` is not able to display cross domain and there is nothing we can do to stop this behavior.

On the bright side, the current method `window.open` is even better for mobile users, it will navigate them to the native app to share which give them better experience

Another good news is that I have rewritten this plugin from scratch with share counts and will update it very soon. :octocat:
