### ISSUE TITLE
ng2-sharebuttons/dist.js not found

### ISSUE THREAD

**Issue by venusseo** [MurhafSousli/ng2-sharebuttons#10]
![screen shot 2016-11-06 at 7 38 11 pm](https://cloud.githubusercontent.com/assets/3885690/20037503/42d9bdfc-a45b-11e6-934a-a360e77d4f6f.png)
![screen shot 2016-11-06 at 7 59 08 pm](https://cloud.githubusercontent.com/assets/3885690/20037549/8582dc78-a45c-11e6-932e-a5c4bcdccb53.png)

**Comment by MurhafSousli** [comment]
Hi @venusseo.
Indeed, there is no such file called `dist.js` because it's a directory.  :astonished:
`index.ts` just exports what is inside `dist` so the following change happens:

without `index.ts`, you have to import the module like this
```javascript
import {ShareButtonsModule} from "ng2-sharebuttons/dist";
```
with `index.ts` you can import the module like this
```javascript
import {ShareButtonsModule} from "ng2-sharebuttons";
```
If you still have problem, show me your code where you are using the module so I can help you.
