### ISSUE TITLE
share buttons did not work in Google+ and twitter

### ISSUE THREAD

**Issue by YoussefSalahHanna** [MurhafSousli/ng2-sharebuttons#112]
i use   MetaModule , you can see meta in the debugger  but in view page source you can not see this meta

![sharebuttons_twitter](https://cloud.githubusercontent.com/assets/28009104/25389321/8cf4d14c-29d0-11e7-83ae-6151ff17cac0.png)

**Comment by MurhafSousli** [comment]
Hi @YoussefSalahHanna, first I don't know which `MetaModule` you mean, but I will assume it is a module to change the meta tags dynamically (at run time). This will not help you in this case because any service will read the shared link will not recognize the updated tags from the `MetaModule`

**Comment by Sathishchary** [comment]
Hi @MurhafSousli, I am also working on the same issue.I am following this links for meta tags dynamically changing. [ngx-meta](https://github.com/ngx-meta/core) and [Angular Meta Service](https://angular.io/docs/ts/latest/api/platform-browser/index/Meta-class.html#!#addTag-anchor) and setting the meta tags dynamically in my component. but it's not working. `This will not help you in this case because any service will read the shared link will not recognize the updated tags from the MetaModule` means?
So is there any another way to show the meta tags dynamically in ng2 share buttons window?

**Comment by MurhafSousli** [comment]
@Sathishchary I think you misunderstood how it works, the issue is not about this share buttons module, it is about the service that is reading the meta tags from the URL you just shared, if the meta tags was not presented in the page's head then it will not be recognized.

Now all these modules _ngx-meta, ng2-meta, Angular Meta Service ...etc_ , they all change the tags dynamically (using javascript) which is not supported in all services, for instance [facebook share debugger](https://developers.facebook.com/tools/debug/sharing/) reads only the static html of your URL (no javascript execution).

luckily, facebook can read the tags from the **link arguments** instead of the meta tags that is in the head, for example: 
```html
<share-buttons [url]="theURL" [title]="theTitle" [image]="theImage"></share-buttons>
```
Now the sharebuttons module will generate a link with the tags as arguments for the service you choice, it will look something like this `https://www.facebook.com/sharer/sharer.php?u=https://example.com&description=this is an example&image=https://cdn.blabla/cover-image.jpg`
which solves the problem.

however this is not the case for google plus, google+ does not read the link arguments like facebook, instead of that it only read them from the meta tags. 

So this is more likely a SEO issue, and the ideal solution here is to use Angular Universal (server side rendering) where the tags are coming from the server.

For @YoussefSalahHanna you can fix twitter by bind the `[title]` input (image is not supported for twitter)
