### ISSUE TITLE
AOT

### ISSUE THREAD

**Issue by kodeine** [MurhafSousli/ng2-sharebuttons#14]
Do you plan to add AOT support?

**Comment by MurhafSousli** [comment]
@kodeine I still haven't touch AOT yet, I'm currently working on other projects, I need someone to collaborate on this, can you?

**Comment by MurhafSousli** [comment]
@kodeine I looked in [AOT](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) and it seems that your problem with AOT is not related to this package, because there is no differences in `@ngModule` that supports AOT and the one that dones't. In this package we don't bootstrap or specify any configuration, it should support AOT by default, `ShareButtonsModule` is just about two components and a service.
