### ISSUE TITLE
Google Plus is not working

### ISSUE THREAD

**Issue by vasua592** [MurhafSousli/ng2-sharebuttons#74]
Hi i am try to post in google plus but the post is not share in share dialog .

twitter and linkdin count is not showing in front end
plz help me urgent

**Comment by MurhafSousli** [comment]
@vasua592 for counts, you must have angular >= **2.4.8**. 
For google plus show me your code

**Comment by vasua592** [comment]
this is my html code 
<share-buttons class="withCount" [defaultStyle]="false" [facebook]="fbTemp" [twitter]="twttTemp" [pinterest]="false"
    [linkedIn]="inTemp" [google]="googleTemp" [tumblr]="false" [whatsApp]="false" [reddit]="false" [stumbleUpOn]="false" [whatsApp]="false"
    [stumbleUpOn]="false" [showCount]="true" (count)="sumCounts($event)">
    </share-buttons>

**Comment by vasua592** [comment]
https://murhafsousli.github.io/ng2-sharebuttons/

In this link also google plus button is not working when u showing a count

**Comment by vasua592** [comment]
I am using 2.3.1 but i want count to show could u do any thing

**Comment by MurhafSousli** [comment]
@vasua592 google plus button is working, but for some unknown reason only twitter link is being invalid on g+ share dialog. I will update the demo with different link later.
for counts. NO you must update your angular! this problem is not related to this module. it was a bug from angular team and they fixed it in the last release. read more [#13219](https://github.com/angular/angular/issues/#13219)
